import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import { MemoryVfs } from '../src/node-runtime/vfs';
import { NodeRuntime } from '../src/node-runtime/runtime';

/**
 * SHA-3 / Keccak / SHAKE / keccak-kmac digests (M90.5). The differential
 * corpus (tools/crypto-hashes-probe.cjs -> test/fixtures/crypto-hashes.json)
 * pins every name against real Node; the unit checks below spot-check the
 * published vectors so a fixture regenerated by mistake cannot hide a bug.
 */
const fromHex = (h: string) => Uint8Array.from(h.match(/../g)!.map((b) => parseInt(b, 16)));
const hex = (b: Uint8Array) => Array.from(b, (x) => x.toString(16).padStart(2, '0')).join('');

function boot() {
  const vfs = new MemoryVfs({ cwd: '/project' });
  vfs.mkdir('/project', { recursive: true });
  const runtime = new NodeRuntime({
    vfs,
    argv: ['/project/index.js'],
    installGlobals: false,
    onStdout: () => {},
    onStderr: () => {},
  });
  return runtime.realm.require('crypto') as any;
}

describe('crypto.createHash SHA-3 family (differential vs real Node)', () => {
  it('matches the oracle exactly', async () => {
    const program = fs.readFileSync('tools/crypto-hashes-probe.cjs', 'utf8');
    const expected = JSON.parse(fs.readFileSync('test/fixtures/crypto-hashes.json', 'utf8'));

    const vfs = new MemoryVfs({ cwd: '/project' });
    vfs.mkdir('/project', { recursive: true });
    vfs.writeFile('/project/index.js', new TextEncoder().encode(program));
    const out: string[] = [];
    const runtime = new NodeRuntime({
      vfs,
      argv: ['/project/index.js'],
      installGlobals: false,
      onStdout: (c) => out.push(c),
      onStderr: () => {},
    });
    runtime.runMain('/project/index.js');

    let stdout = out.join('');
    for (let i = 0; i < 400 && !stdout.includes('__OBS__'); i++) {
      await new Promise((r) => setTimeout(r, 25));
      stdout = out.join('');
    }
    const line = stdout.split('\n').find((l) => l.startsWith('__OBS__'));
    expect(line, 'probe produced no observation line').toBeTruthy();
    expect(JSON.parse(line!.slice('__OBS__'.length))).toEqual(expected);
  }, 60000);
});

describe('crypto.createHash digests unit surface', () => {
  it('computes the FIPS 202 vectors', () => {
    const crypto = boot();
    expect(crypto.createHash('sha3-256').update('abc').digest('hex')).toBe(
      '3a985da74fe225b2045c172d6bd390bd855f086e3e9d525b46bfe24511431532',
    );
    expect(crypto.createHash('sha3-512').update('').digest('hex')).toBe(
      'a69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26',
    );
    // Original Keccak (0x01 padding) differs from SHA-3 on the same input.
    expect(crypto.createHash('keccak-256').update('').digest('hex')).toBe(
      'c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470',
    );
  });

  it('supports XOF output lengths', () => {
    const crypto = boot();
    expect(crypto.createHash('shake128', { outputLength: 32 }).update('abc').digest('hex')).toBe(
      '5881092dd818bf5cf8a3ddb793fbcba74097d5c526a6d35f97b83351940f2cc8',
    );
    // Defaults: 16 bytes for shake128, 32 for shake256.
    expect(crypto.createHash('shake128').update('abc').digest().length).toBe(16);
    expect(crypto.createHash('shake256').update('abc').digest().length).toBe(32);
  });

  it('rejects outputLength on a fixed digest', () => {
    const crypto = boot();
    expect(() => crypto.createHash('sha3-256', { outputLength: 16 })).toThrowError(/not XOF/i);
  });

  it('resolves the OpenSSL aliases', () => {
    const crypto = boot();
    const expected = crypto.createHash('sha3-256').update('abc').digest('hex');
    expect(crypto.createHash('RSA-SHA3-256').update('abc').digest('hex')).toBe(expected);
    expect(crypto.createHash('id-rsassa-pkcs1-v1_5-with-sha3-256').update('abc').digest('hex')).toBe(expected);
    expect(hex(fromHex(expected))).toBe(expected);
  });

  it('computes SM3, RIPEMD-160 and BLAKE2 vectors', () => {
    const crypto = boot();
    expect(crypto.createHash('sm3').update('abc').digest('hex')).toBe(
      '66c7f0f462eeedd9d1f2d46bdc10e4e24167c4875cf2f7a2297da02b8f4ba8e0',
    );
    expect(crypto.createHash('ripemd160').update('').digest('hex')).toBe(
      '9c1185a5c5e9fc54612808977ee8f548b2258d31',
    );
    expect(crypto.createHash('rmd160').update('abc').digest('hex')).toBe(
      '8eb208f7e05d987a9b044a8e98c6b087f15a0bfc',
    );
    expect(crypto.createHash('blake2b512').update('abc').digest('hex')).toBe(
      'ba80a53f981c4d0d6a2797b69f12f6e94c212f14685ac4b74b12bb6fdbffa2d17d87c5392aab792dc252d5de4533cc9518d38aa8dbf1925ab92386edd4009923',
    );
  });
});
