import type { BuiltinSpec } from './types';

/**
 * Builtins backed by real Node.js source (see tools/vendor.mjs).
 * Provenance is recorded in vendor/node-lib/MANIFEST.json.
 */

export const vendoredBuiltins: BuiltinSpec[] = [
  {
    id: 'internal/constants',
    vendorPath: 'internal/constants.js',
    origin: 'node-source',
  },
  {
    id: 'internal/encoding/util',
    vendorPath: 'internal/encoding/util.js',
    origin: 'node-source',
  },
  {
    id: 'internal/querystring',
    vendorPath: 'internal/querystring.js',
    origin: 'node-source',
    deps: ['internal/errors'],
  },
  {
    id: 'internal/util/types',
    vendorPath: 'internal/util/types.js',
    origin: 'node-source',
  },
  {
    id: 'internal/util/inspect',
    vendorPath: 'internal/util/inspect.js',
    origin: 'node-source',
    deps: [
      'internal/util',
      'internal/util/types',
      'internal/errors',
      'internal/assert',
      'internal/bootstrap/realm',
      'internal/validators',
      'buffer',
    ],
  },
  {
    id: 'internal/util/colors',
    vendorPath: 'internal/util/colors.js',
    origin: 'node-source',
    // `internal/tty` is only pulled in when FORCE_COLOR is set, which never
    // happens in the browser, so it is deliberately left unregistered.
    deps: [],
  },
  {
    id: 'internal/validators',
    vendorPath: 'internal/validators.js',
    origin: 'node-source',
    deps: ['internal/errors', 'internal/util', 'internal/util/types'],
  },
  {
    id: 'internal/assert',
    vendorPath: 'internal/assert.js',
    origin: 'node-source',
    deps: ['internal/errors'],
  },
  {
    id: 'internal/assert/myers_diff',
    vendorPath: 'internal/assert/myers_diff.js',
    origin: 'node-source',
    deps: ['internal/errors', 'internal/util/colors'],
  },
  {
    id: 'internal/assert/assertion_error',
    vendorPath: 'internal/assert/assertion_error.js',
    origin: 'node-source',
    deps: [
      'internal/errors',
      'internal/util',
      'internal/util/colors',
      'internal/util/inspect',
      'internal/validators',
      'internal/assert/myers_diff',
    ],
  },
  {
    id: 'internal/assert/utils',
    vendorPath: 'internal/assert/utils.js',
    origin: 'node-source',
    deps: [
      'internal/errors',
      'internal/errors/error_source',
      'internal/util',
      'internal/util/inspect',
      'internal/assert/assertion_error',
    ],
  },
  {
    id: 'internal/util/comparisons',
    vendorPath: 'internal/util/comparisons.js',
    origin: 'node-source',
    // `internal/crypto/keys` is only reached for real KeyObject/CryptoKey
    // values, which this runtime never produces (no OpenSSL).
    deps: ['buffer', 'internal/assert', 'internal/url', 'internal/util', 'internal/util/types'],
  },
  {
    id: 'assert',
    vendorPath: 'assert.js',
    origin: 'node-source',
    deps: [
      'internal/assert',
      'internal/assert/utils',
      'internal/errors',
      'internal/util',
      'internal/util/comparisons',
      'internal/util/inspect',
      'internal/util/types',
      'internal/validators',
    ],
  },
  {
    id: 'internal/streams/state',
    vendorPath: 'internal/streams/state.js',
    origin: 'node-source',
    deps: ['internal/errors', 'internal/validators'],
  },
  {
    id: 'internal/streams/from',
    vendorPath: 'internal/streams/from.js',
    origin: 'node-source',
    deps: ['buffer', 'internal/errors'],
  },
  {
    id: 'internal/streams/utils',
    vendorPath: 'internal/streams/utils.js',
    origin: 'node-source',
  },
  {
    id: 'internal/streams/destroy',
    vendorPath: 'internal/streams/destroy.js',
    origin: 'node-source',
    deps: ['internal/errors', 'internal/streams/utils'],
  },
  {
    id: 'internal/streams/end-of-stream',
    vendorPath: 'internal/streams/end-of-stream.js',
    origin: 'node-source',
    deps: [
      'internal/errors',
      'internal/util',
      'internal/validators',
      'internal/streams/utils',
      'internal/async_hooks',
      'internal/async_context_frame',
      'internal/events/abort_listener',
    ],
  },
  {
    id: 'internal/streams/legacy',
    vendorPath: 'internal/streams/legacy.js',
    origin: 'node-source',
    deps: ['events'],
  },
  {
    id: 'internal/streams/add-abort-signal',
    vendorPath: 'internal/streams/add-abort-signal.js',
    origin: 'node-source',
    deps: [
      'internal/errors',
      'internal/streams/utils',
      'internal/streams/end-of-stream',
      'internal/events/abort_listener',
    ],
  },
  {
    id: 'internal/fixed_queue',
    vendorPath: 'internal/fixed_queue.js',
    origin: 'node-source',
  },
  {
    id: 'internal/streams/readable',
    vendorPath: 'internal/streams/readable.js',
    origin: 'node-source',
    deps: [
      'events',
      'buffer',
      'string_decoder',
      'internal/errors',
      'internal/validators',
      'internal/options',
      'internal/util/debuglog',
      'internal/streams/legacy',
      'internal/streams/state',
      'internal/streams/utils',
      'internal/streams/destroy',
      'internal/streams/end-of-stream',
      'internal/streams/add-abort-signal',
      'internal/streams/from',
      'internal/fixed_queue',
    ],
  },
  {
    id: 'internal/streams/writable',
    vendorPath: 'internal/streams/writable.js',
    origin: 'node-source',
    deps: [
      'events',
      'buffer',
      'internal/util',
      'internal/errors',
      'internal/streams/legacy',
      'internal/streams/destroy',
      'internal/streams/end-of-stream',
      'internal/streams/add-abort-signal',
      'internal/streams/state',
      'internal/streams/utils',
    ],
  },
  {
    id: 'internal/streams/duplex',
    vendorPath: 'internal/streams/duplex.js',
    origin: 'node-source',
    deps: [
      'internal/streams/legacy',
      'internal/streams/readable',
      'internal/streams/writable',
      'internal/streams/add-abort-signal',
      'internal/streams/destroy',
      'internal/streams/utils',
    ],
  },
  {
    id: 'internal/streams/transform',
    vendorPath: 'internal/streams/transform.js',
    origin: 'node-source',
    deps: ['internal/errors', 'internal/streams/duplex', 'internal/streams/state'],
  },
  {
    id: 'internal/streams/passthrough',
    vendorPath: 'internal/streams/passthrough.js',
    origin: 'node-source',
    deps: ['internal/streams/transform'],
  },
  {
    id: 'internal/streams/pipeline',
    vendorPath: 'internal/streams/pipeline.js',
    origin: 'node-source',
    deps: [
      'internal/errors',
      'internal/validators',
      'internal/util',
      'internal/abort_controller',
      'internal/streams/end-of-stream',
      'internal/streams/destroy',
      'internal/streams/duplex',
      'internal/streams/utils',
      'internal/streams/readable',
      'internal/events/abort_listener',
      'internal/streams/passthrough',
    ],
  },
  {
    id: 'internal/streams/compose',
    vendorPath: 'internal/streams/compose.js',
    origin: 'node-source',
    deps: [
      'internal/errors',
      'internal/streams/pipeline',
      'internal/streams/duplex',
      'internal/streams/destroy',
      'internal/streams/utils',
      'internal/streams/end-of-stream',
    ],
  },
  {
    id: 'internal/streams/operators',
    vendorPath: 'internal/streams/operators.js',
    origin: 'node-source',
    deps: [
      'internal/errors',
      'internal/validators',
      'internal/event_target',
      'internal/abort_controller',
      'internal/streams/end-of-stream',
    ],
  },
  {
    id: 'internal/streams/duplexpair',
    vendorPath: 'internal/streams/duplexpair.js',
    origin: 'node-source',
    deps: ['internal/assert', 'stream'],
  },
  {
    id: 'internal/streams/duplexify',
    vendorPath: 'internal/streams/duplexify.js',
    origin: 'node-source',
    deps: [
      'internal/errors',
      'internal/blob',
      'internal/abort_controller',
      'internal/streams/utils',
      'internal/streams/end-of-stream',
      'internal/streams/destroy',
      'internal/streams/duplex',
      'internal/streams/readable',
      'internal/streams/writable',
      'internal/streams/from',
    ],
  },
  {
    id: 'stream',
    aliases: ['node:stream'],
    vendorPath: 'stream.js',
    origin: 'node-source',
    deps: [
      'internal/util',
      'internal/util/types',
      'internal/buffer',
      'internal/errors',
      'internal/streams/operators',
      'internal/streams/compose',
      'internal/streams/state',
      'internal/streams/pipeline',
      'internal/streams/destroy',
      'internal/streams/end-of-stream',
      'internal/streams/utils',
      'internal/streams/legacy',
      'internal/streams/readable',
      'internal/streams/writable',
      'internal/streams/duplex',
      'internal/streams/transform',
      'internal/streams/passthrough',
      'internal/streams/add-abort-signal',
      'stream/promises',
    ],
  },
  {
    id: 'stream/promises',
    aliases: ['node:stream/promises'],
    vendorPath: 'stream/promises.js',
    origin: 'node-source',
    deps: ['internal/errors', 'internal/streams/utils', 'internal/streams/pipeline', 'internal/streams/end-of-stream'],
  },
  {
    id: 'internal/async_hooks',
    vendorPath: 'internal/async_hooks.js',
    origin: 'node-source',
    // No eager deps: Node requires `internal/util/inspect`, `internal/options`
    // and `internal/promise_hooks` lazily from inside this file.
    deps: [],
  },
  {
    id: 'internal/promise_hooks',
    vendorPath: 'internal/promise_hooks.js',
    origin: 'node-source',
    deps: ['internal/util', 'internal/validators'],
  },
  {
    id: 'internal/async_context_frame',
    vendorPath: 'internal/async_context_frame.js',
    origin: 'node-source',
  },
  {
    id: 'internal/async_local_storage/run_scope',
    vendorPath: 'internal/async_local_storage/run_scope.js',
    origin: 'node-source',
  },
  {
    id: 'internal/async_local_storage/async_hooks',
    vendorPath: 'internal/async_local_storage/async_hooks.js',
    origin: 'node-source',
    deps: [
      'internal/validators',
      'internal/async_hooks',
      'async_hooks',
      'internal/async_local_storage/run_scope',
      'internal/util',
    ],
  },
  {
    id: 'async_hooks',
    aliases: ['node:async_hooks'],
    vendorPath: 'async_hooks.js',
    origin: 'node-source',
    deps: [
      'internal/errors',
      'internal/util',
      'internal/validators',
      'internal/async_hooks',
      'internal/async_context_frame',
    ],
  },
  {
    id: 'events',
    aliases: ['node:events'],
    vendorPath: 'events.js',
    origin: 'node-source',
    deps: [
      'internal/errors',
      'internal/util',
      'internal/util/inspect',
      'internal/validators',
      'internal/events/abort_listener',
      'internal/fixed_queue',
      'internal/events/symbols',
      'internal/event_target',
    ],
  },
  {
    id: 'path',
    aliases: ['node:path'],
    vendorPath: 'path.js',
    origin: 'node-source',
    deps: ['internal/constants', 'internal/validators', 'internal/util', 'internal/fs/glob'],
  },
  {
    id: 'querystring',
    aliases: ['node:querystring'],
    vendorPath: 'querystring.js',
    origin: 'node-source',
    deps: ['buffer', 'internal/querystring'],
  },
  {
    id: 'punycode',
    aliases: ['node:punycode'],
    vendorPath: 'punycode.js',
    origin: 'node-source',
    deps: [],
  },
  {
    id: 'domain',
    aliases: ['node:domain'],
    vendorPath: 'domain.js',
    origin: 'node-source',
    deps: [
      'events',
      'async_hooks',
      'internal/errors',
      'internal/util',
      'internal/async_hooks',
    ],
  },
  {
    id: 'diagnostics_channel',
    aliases: ['node:diagnostics_channel'],
    vendorPath: 'diagnostics_channel.js',
    origin: 'node-source',
    deps: [
      'internal/errors',
      'internal/validators',
      'internal/util',
      'internal/util/types',
      'async_hooks',
    ],
  },
  {
    id: 'string_decoder',
    aliases: ['node:string_decoder'],
    vendorPath: 'string_decoder.js',
    origin: 'node-source',
    deps: ['buffer', 'internal/util', 'internal/errors'],
  },
];
