import type { BindingFactory } from './context';

/** Static platform/config flags consumed by internal Node lib code. */
export const configBinding: BindingFactory = () => ({
  isWindows: false,
  isMacOS: false,
  isLinux: true,
  isFreeBSD: false,
  isOpenBSD: false,
  isAIX: false,
  isSunOS: false,
  isAndroid: false,
  hasIntl: true,
  hasSmallICU: false,
  hasStringBytes: true,
  hasUtf8Write: true,
  hasIntlDateFormat: true,
  hasIntlDateTimeFormat: true,
  hasIntlCollator: true,
  hasIntlLocale: true,
  hasIntlListFormat: true,
  hasIntlRelativeTimeFormat: true,
  hasIntlPluralRules: true,
  hasIntlDisplayNames: true,
  hasIntlSegmenter: true,
  hasTemporal: false,
  hasWebStorage: false,
  hasSQLite: false,
  experimentalWasmWebEmbedding: false,
  hasOpenSSL: false,
  hasCrypto: false,
  hasUserInfo: true,
  hasFfi: false,
  hasInspector: false,
  hasNetworkFamily: false,
  hasQuic: false,
  hasDtls: false,
  hasVfs: true,
  hasSea: false,
  hasPnpm: false,
  sharedArrayBufferMode: 0,
  vendor: 'web-node',
  target_arch: 'wasm32',
  platform: 'browser',
});
